name: 'retail_agent_gold'
version: '1.0.0'
config-version: 2

profile: 'retail_agent_gold'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  retail_agent_gold:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: gold
