version: 2

models:
  - name: dim_symbols
    columns:
      - name: symbol
        tests: [unique, not_null]

  - name: dim_date
    columns:
      - name: date_key
        tests: [unique, not_null]

  - name: fct_trades
    columns:
      - name: trade_id
        tests: [unique, not_null]
      - name: symbol
        tests:
          - not_null
          - relationships:
              to: ref('dim_symbols')
              field: symbol

  - name: fct_bars
    columns:
      - name: symbol
        tests:
          - not_null
          - relationships:
              to: ref('dim_symbols')
              field: symbol
      - name: bar_ts
        tests: [not_null]
