-- Step 7: Governance — RBAC + Data Masking
-- Controls who/what (including the Cortex Analyst agent's role) can see raw PII.
-- Two masking policies here mirror real banking compliance: email (general PII)
-- and SSN (regulated identifier, PCI/GLBA-adjacent) get different unmask scopes.

-- Roles
CREATE ROLE IF NOT EXISTS LOADER;       -- Snowpipe / ingestion identity
CREATE ROLE IF NOT EXISTS TRANSFORMER;  -- dbt runs as this role
CREATE ROLE IF NOT EXISTS ANALYST_AGENT; -- Cortex Analyst queries as this role
CREATE ROLE IF NOT EXISTS BI_READER;    -- human dashboard/BI users

GRANT USAGE ON DATABASE BANK_AGENT TO ROLE LOADER;
GRANT USAGE, CREATE TABLE, CREATE STREAM, CREATE TASK ON SCHEMA BANK_AGENT.BRONZE TO ROLE LOADER;

GRANT USAGE ON DATABASE BANK_AGENT TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA BANK_AGENT.SILVER TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA BANK_AGENT.SILVER TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE BANK_AGENT TO ROLE TRANSFORMER;

GRANT USAGE ON DATABASE BANK_AGENT TO ROLE ANALYST_AGENT;
GRANT USAGE ON SCHEMA BANK_AGENT.GOLD TO ROLE ANALYST_AGENT;
GRANT SELECT ON ALL TABLES IN SCHEMA BANK_AGENT.GOLD TO ROLE ANALYST_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BANK_AGENT.GOLD TO ROLE ANALYST_AGENT;

GRANT USAGE ON DATABASE BANK_AGENT TO ROLE BI_READER;
GRANT USAGE ON SCHEMA BANK_AGENT.GOLD TO ROLE BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA BANK_AGENT.GOLD TO ROLE BI_READER;

-- Email: masked for everyone except a compliance-style unmask role.
CREATE MASKING POLICY IF NOT EXISTS BANK_AGENT.GOLD.EMAIL_MASK AS (val VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN IS_ROLE_IN_SESSION('PII_UNMASKED') THEN val
    ELSE REGEXP_REPLACE(val, '^.+(@.+)$', '***\\1')
  END;

-- SSN: fully redacted for everyone except the same compliance role, and never
-- partially revealed (unlike email) since it's a regulated identifier.
CREATE MASKING POLICY IF NOT EXISTS BANK_AGENT.GOLD.SSN_MASK AS (val VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN IS_ROLE_IN_SESSION('PII_UNMASKED') THEN val
    ELSE 'XXX-XX-' || RIGHT(val, 4)
  END;

ALTER TABLE BANK_AGENT.GOLD.DIM_CUSTOMERS MODIFY COLUMN email
  SET MASKING POLICY BANK_AGENT.GOLD.EMAIL_MASK;

ALTER TABLE BANK_AGENT.GOLD.DIM_CUSTOMERS MODIFY COLUMN ssn
  SET MASKING POLICY BANK_AGENT.GOLD.SSN_MASK;

CREATE ROLE IF NOT EXISTS PII_UNMASKED; -- grant sparingly, e.g. to a compliance role

-- The agent role explicitly does NOT get PII_UNMASKED: Cortex Analyst should
-- never see raw email or SSN, only aggregate/behavioral columns.
