-- Step 7: Governance — RBAC + Data Masking
-- Controls who/what (including the Cortex Analyst agent's role) can see raw PII.

-- Roles
CREATE ROLE IF NOT EXISTS LOADER;       -- Snowpipe / ingestion identity
CREATE ROLE IF NOT EXISTS TRANSFORMER;  -- dbt runs as this role
CREATE ROLE IF NOT EXISTS ANALYST_AGENT; -- Cortex Analyst queries as this role
CREATE ROLE IF NOT EXISTS BI_READER;    -- human dashboard/BI users

GRANT USAGE ON DATABASE RETAIL_AGENT TO ROLE LOADER;
GRANT USAGE, CREATE TABLE, CREATE STREAM, CREATE TASK ON SCHEMA RETAIL_AGENT.BRONZE TO ROLE LOADER;

GRANT USAGE ON DATABASE RETAIL_AGENT TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_AGENT.SILVER TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AGENT.SILVER TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE RETAIL_AGENT TO ROLE TRANSFORMER;

GRANT USAGE ON DATABASE RETAIL_AGENT TO ROLE ANALYST_AGENT;
GRANT USAGE ON SCHEMA RETAIL_AGENT.GOLD TO ROLE ANALYST_AGENT;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AGENT.GOLD TO ROLE ANALYST_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_AGENT.GOLD TO ROLE ANALYST_AGENT;

GRANT USAGE ON DATABASE RETAIL_AGENT TO ROLE BI_READER;
GRANT USAGE ON SCHEMA RETAIL_AGENT.GOLD TO ROLE BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_AGENT.GOLD TO ROLE BI_READER;

-- Data masking: the agent role and general BI readers never see raw email;
-- only roles explicitly granted the unmask privilege do.
CREATE MASKING POLICY IF NOT EXISTS RETAIL_AGENT.GOLD.EMAIL_MASK AS (val VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN IS_ROLE_IN_SESSION('PII_UNMASKED') THEN val
    ELSE REGEXP_REPLACE(val, '^.+(@.+)$', '***\\1')
  END;

ALTER TABLE RETAIL_AGENT.GOLD.DIM_CUSTOMERS MODIFY COLUMN email
  SET MASKING POLICY RETAIL_AGENT.GOLD.EMAIL_MASK;

CREATE ROLE IF NOT EXISTS PII_UNMASKED; -- grant sparingly, e.g. to a compliance role
